<a href="https://colab.research.google.com/github/gxth969-pixel/ict_assignments/blob/main/assignment33.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/content/employee (1).csv')

In [5]:
print('First 5 rows of the dataset:')
display(df.head())

First 5 rows of the dataset:

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

In [6]:
print('\nInformation about the dataset:')
df.info()

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               9 non-null      object
 1   age                7 non-null      float64
 2   income             7 non-null      float64
 3   gender             7 non-null      object
 4   department         9 non-null      object
 5   grade              9 non-null      object
 6   performance_score  9 non-null      int64
dtypes: float64(2), int64(1), object(4)
memory usage: 636.0+ bytes

In [7]:
print('\nDescriptive statistics of the dataset:')
display(df.describe())

Descriptive statistics of the dataset:

             age        income  performance_score
count   7.000000      7.000000           9.000000
mean   40.428571  52857.142857         610.666667
std    12.204605  26028.372797         235.671912
min    23.000000  16000.000000          53.000000
25%    31.000000  38500.000000         556.000000
50%    45.000000  52000.000000         674.000000
75%    49.500000  63500.000000         711.000000
max    54.000000  98000.000000         901.000000

question 2

In [8]:
df.set_index('name', inplace=True)
print('DataFrame after setting "name" as index:')
display(df.head())

DataFrame after setting "name" as index:

                age   income gender  department grade  performance_score
name
Allen Smith    45.0      NaN    NaN  Operations    G3                723
S Kumar         NaN  16000.0      F     Finance    G0                520
Jack Morgan    32.0  35000.0      M     Finance    G2                674
Ying Chin      45.0  65000.0      F       Sales    G3                556
Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

question 3

In [9]:
print('Employees with performance score greater than 700:')
display(df[df['performance_score'] > 700])

Employees with performance score greater than 700:

                age   income gender  department grade  performance_score
name
Allen Smith    45.0      NaN    NaN  Operations    G3                723
Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
Josh Wills     54.0  52000.0      F     Finance    G3                901
Leo Duck       23.0  98000.0      M       Sales    G4                709

question 4

In [10]:
print('Employees with performance score greater than 500 and less than 700:')
display(df[(df['performance_score'] > 500) & (df['performance_score'] < 700)])

Employees with performance score greater than 500 and less than 700:

                age   income gender department grade  performance_score
name
S Kumar         NaN  16000.0      F    Finance    G0                520
Jack Morgan    32.0  35000.0      M    Finance    G2                674
Ying Chin      45.0  65000.0      F      Sales    G3                556
Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649

question 5

In [11]:
print('Missing values in each column:')
display(df.isnull().sum())

Missing values in each column:

age                  2
income               2
gender               2
department           0
grade                0
performance_score    0
dtype: int64

question 6

In [12]:
print('First 5 rows of the DataFrame after outlier handling:')
display(df.head())

First 5 rows of the DataFrame after outlier handling:

                age   income gender  department grade  performance_score
name
Allen Smith    45.0      NaN    NaN  Operations    G3                723
S Kumar         NaN  16000.0      F     Finance    G0                520
Jack Morgan    32.0  35000.0      M     Finance    G2                674
Ying Chin      45.0  65000.0      F       Sales    G3                556
Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

question 7

In [13]:
if 'gender' in df.columns:
    print('Unique values in the gender column:')
    display(df['gender'].unique())

    df = pd.get_dummies(df, columns=['gender'], prefix='gender')
    print('\nOne-hot encoding completed.')
else:
    print('"gender" column not found. It might already be encoded.')
    print('Current columns:', df.columns.tolist())

display(df.head())

Unique values in the gender column:

array([nan, 'F', 'M'], dtype=object)

One-hot encoding completed.

,age,income,department,grade,performance_score,gender_F,gender_M
name,,,,,,,
Allen Smith,45.0,NaN,Operations,G3,723,False,False
S Kumar,NaN,16000.0,Finance,G0,520,True,False
Jack Morgan,32.0,35000.0,Finance,G2,674,False,True
Ying Chin,45.0,65000.0,Sales,G3,556,True,False
Dheeraj Patel,30.0,42000.0,Operations,G2,711,True,False